config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :places do
      resources :varieties, except: [:index, :show]
    end
    root 'places#index'
  end
  resources :orders, only: [:index, :new, :create, :show], param: :slug do
    get :new_custom_place, on: :collection, to: 'orders#new_custom_place'
    post :finish, on: :member
    post :create_join, on: :member
    post :send_order_slug, on: :collection
  end
  root 'orders#index'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :varieties
  validates :name, presence: true
  validate :phone_or_address
  private
  def phone_or_address
    if phone.blank? and address.blank? 
      errors.add(I18n.t('activerecord.models.place.phone'), I18n.t('errors.messages.or') + " #{I18n.t('activerecord.models.place.address')}")
    end
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = I18n.t('activerecord.messages.create_place') + " #{@place.name}"
      redirect_to admin_places_path
    else
      render 'new'
    end
  end

  def show
    @place = Place.find_by(id: params[:id])
    if !@place
      flash[:danger] = I18n.t('activerecord.errors.messages.url')
      redirect_to admin_places_path
    end
  end

  def edit
    @place = Place.find_by(id: params[:id])
    if !@place
      flash[:danger] = I18n.t('activerecord.errors.messages.url')
      redirect_to admin_places_path
    end
  end

  def update
    @place = Place.find_by(id: params[:id])
    if !@place
      flash[:danger] = I18n.t('activerecord.errors.messages.url')
      redirect_to admin_places_path
    else
      if @place.update(place_params)
        flash[:success] = I18n.t('activerecord.messages.update_place') + " #{@place.name}"
        redirect_to admin_places_path
      else
        render 'edit'
      end
    end
  end

  def destroy
    @place = Place.find_by(id: params[:id])
    if !@place
      flash[:danger] = I18n.t('activerecord.errors.messages.url')
    else
      if @place.destroy
        flash[:success] = I18n.t('activerecord.messages.delete_place') + " #{@place.name}"
      else 
        flash[:danger] = I18n.t('activerecord.errors.messages.delete_place') + " #{@place.name}"
      end
    redirect_to admin_places_path
    end
  end

  private

  def place_params
    params.require(:place).permit(:name, :phone, :address)
  end

end

app/views/admin/places/_form.html.erb
<%= show_errors_for_form(f) %> 
<div class="form-group">
  <%= f.label :name, I18n.t('activerecord.models.place.name') %>
  <%= f.text_field :name, required: true, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :phone, I18n.t('activerecord.models.place.phone') %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :address, I18n.t('activerecord.models.place.address')%>
  <%= f.text_field :address, class: 'form-control' %>
</div>

app/views/admin/places/edit.html.erb
<div class="row justify-content-center">
  <div class="col col-8">
    <h1><%= I18n.t('tittle.edit_place') %></h1>
    <%= form_for([:admin, @place]) do |f| %>
      <%= render partial: 'form', locals: {f: f} %>
      <%= f.submit I18n.t('button.update_place'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/places/index.html.erb
<div class="row">
  <div class="col">
    <h1><%= I18n.t('tittle.list_place') %></h1>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <%= link_to  new_admin_place_path, class: 'btn btn-primary btn-sm' do %>
      <i class="fas fa-plus-square"></i>
      <%= I18n.t('button.add_place') %>
    <% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col"><%= I18n.t('table.name') %></th>
        <th scope="col"><%= I18n.t('table.phone') %></th>
        <th scope="col"><%= I18n.t('table.address') %></th>
        <th scope="col"><%= I18n.t('table.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.phone %></td>
          <td><%= place.address %></td>
          <td>
            <%= link_to admin_place_path(place), class: 'btn btn-secondary btn-sm', title: I18n.t('button.view_place') do %>
              <i class="fas fa-eye"></i>
            <% end %>
            <%= link_to new_admin_place_variety_path(place.id), class: 'btn btn-secondary btn-sm',
                        title: I18n.t('button.add_variety') do %>
              <i class="fas fa-plus-square"></i>
            <% end %>
            <%= link_to edit_admin_place_path(place.id), class: 'btn btn-secondary btn-sm', title: I18n.t('button.edit_place') do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to admin_place_path(place), method: :delete,
                        data: {confirm: I18n.t('message.confirm_delete_place')}, class: 'btn btn-danger btn-sm', title: I18n.t('button.delete_place') do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/places/new.html.erb
<div class="row justify-content-center">
  <div class="col col-8">
    <h1><%= I18n.t('tittle.add_place') %></h1>
    <%= form_for([:admin, @place]) do |f| %>
      <%= render partial: 'form', locals: {f: f} %>
      <%= f.submit I18n.t('button.add_place'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/places/show.html.erb
<h1><%= @place.name %></h1>
<p><i class="fas fa-phone"></i> <%= @place.phone %></p>
<p><i class="fas fa-map-marker-alt"></i> <%= @place.address %></p>
<h4><%= I18n.t('tittle.list_variety') %></h4>

<p>
  <%= link_to new_admin_place_variety_path(@place.id), class: 'btn btn-primary btn-sm' do %>
    <i class="fas fa-plus-square"></i>
    <%= I18n.t('button.add_variety') %>    
  <% end %>
</p>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= I18n.t('table.name') %></th>
    <th scope="col"><%= I18n.t('table.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @place.varieties.each do |variety| %>
    <tr>
      <td><%= variety.name %></td>
      <td>
        <%= link_to edit_admin_place_variety_path(@place.id, variety.id), class: 'btn btn-secondary btn-sm',
                    title: I18n.t('button.edit_variety') do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to admin_place_variety_path(@place.id, variety.id), method: :delete,
                    data: {confirm: I18n.t('message.confirm_delete_variety')}, class: 'btn btn-danger btn-sm', title: I18n.t('button.delete_variety') do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>