config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :places do
      resources :varieties, except: [:index, :show]
    end
    root 'places#index'
  end
  resources :orders, only: [:index, :new, :create, :show], param: :slug do
    get :new_custom_place, on: :collection, to: 'orders#new_custom_place'
    post :finish, on: :member
    post :create_join, on: :member
    post :send_order_slug, on: :collection
  end
  root 'orders#index'
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :place, optional: true

  after_create do
    hashids = Hashids.new(ENV['HASH_SALT'], 4, "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    self.slug = hashids.encode(self.id)
    self.open = true
  end

  def set_place= place
    self.place_name = place.name
    self.place_address = place.address
    self.place_phone = place.phone
  end

  def total_units_per_variety
    total_units_per_variety = Hash.new(0)
    self.order_details.each do |detail|
      total_units_per_variety[detail.variety_name] += detail.quantity
    end
    total_units_per_variety
  end
  
  def total_units
    total_units_per_variety.values.sum
  end

  def total_units_per_person
    total_units_per_person = Hash.new(0)
    self.order_details.each do |detail|
        total_units_per_person[detail.person] += detail.quantity
    end
    total_units_per_person
  end

  def price_per_person
    load_prices
    price_per_person = Hash.new(0)
    self.order_details.each do |detail|
        price_per_person[detail.person] += detail.price
    end
    price_per_person
  end

  def load_prices
    price_per_unit = self.price / total_units
    self.order_details.each do |detail|
      detail.price = detail.quantity * price_per_unit
    end
  end

  def list_of_participants
    participants = []
    self.order_details.each do |detail|
        participants << detail.person
    end 
    participants.uniq
  end

  def varieties_to_buy 
    varieties_to_buy =[]
    self.order_details.each do |detail|
      varieties_to_buy << detail.variety_name
    end
    varieties_to_buy.uniq
  end

  def quantity_participants
    list_of_participants.length
  end

  def search_quantity(person_name, variety_name)
    detail = self.order_details.find_by(person: person_name, variety_name: variety_name)
    if detail
      quantity=detail.quantity
    else
      quantity=0
    end
  end

  def was_ordered?
    self.price > 0
  end

  def status
    if was_ordered?
      response = 'finalizada'
    elsif !self.open
      response = 'cerrada'
    else
      response = 'en curso'
    end
    response
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.find(params[:place_id])
    @order = Order.create(place: @place)
    @order.set_place = @place
    @order.save
    session[:participants_added] = session[:participants_added] || Hash.new([])
    session[:orders_created] = session[:orders_created] || []
    session[:orders_created] << @order.slug
    redirect_to order_path(slug: @order.slug)
  end

  def new_custom_place
    @order = Order.create
    @order.place_name = params[:custom_place][:name]
    @order.save
    session[:participants_added] = session[:participants_added] || Hash.new([])
    session[:orders_created] = session[:orders_created] || []
    session[:orders_created] << @order.slug
    redirect_to order_path(@order.slug)
  end

  def create
    fill_order(params[:input_order][:slug])
    if params[:commit] == "Pedir" and @order.quantity_participants > 0
      @order.update(open: false)
    else
      if @order.quantity_participants == 0
        flash[:info] ='Esta orden no tiene preferencias cargadas.
                     Por favor asegurate de que tu o alguien de tu grupo envíe
                     sus preferencias antes de continuar.'
      end
    end 
    redirect_to order_path(@order.slug)
  end

  def edit
    if @order.place_id
      edit_existing_place
    else
      edit_custom_place
    end

  end

  def edit_existing_place
    render 'edit'
  end

  def edit_custom_place
    render 'edit_custom_place'
  end

  def create_join
    if !session[:current_user] && params[:input_order][:name].present?
      session[:current_user] = params[:input_order][:name]
    end
    fill_personal_order_details(params[:input_order][:slug])
    if params[:commit] == "Enviar Preferencias"
      flash[:success] = 'Tus preferencias fueron enviadas al organizador. Sin embargo, puedes seguir editando mientras
      el pedido siga en proceso, y volver a enviar.'
      redirect_to order_path(@order.slug)
    end
  end

  def send_order_slug
    redirect_to order_path(params[:join_order][:slug])
  end

  def join
    render 'join'
  end

  def confirm
    render 'confirm'
  end

  def finish
    @order = Order.find_by(slug: params[:slug])
    if params[:commit] == "Ya ordené el pedido"
      @order.update(price: params[:order_data]['price'].to_i)
      session[:participants_added][params[:slug]] = nil
    else
      reopen(@order)
    end
    redirect_to order_path(@order.slug)
  end

  def view_summary
    render 'finish'
  end

  def reopen(order)
    order.update(open: true)
  end

  def show
    session[:orders_created] = session[:orders_created] || []
    @order = Order.find_by(slug: params[:slug])
    if !@order
      flash[:danger] = I18n.t('activerecord.errors.messages.url')
      redirect_to orders_path
    else
      is_mine = session[:orders_created].include?(params[:slug])
      if @order.open && is_mine
        edit
      elsif !@order.open && !@order.was_ordered? && is_mine
        confirm
      elsif @order.was_ordered? || (!@order.open && !is_mine)
        view_summary
      elsif @order.open && !is_mine
        join
      end
    end

  end

  private

  def fill_personal_order_details(slug)
    @order = Order.find_by(slug: slug)
    person_name = params[:input_order]['name'].presence || session[:current_user]
    params[:input_order].permit!
    params[:input_order]['q'].to_h.map do |variety_id, quantity|
      variety_name = get_variety_name(@order, variety_id)
      detail = search_detail(person_name, variety_name)
      if detail
        update_detail(detail, person_name, quantity)
      else
        if quantity.to_i != 0
          @order.order_details << OrderDetail.new(person: person_name, order_id: @order.id, quantity: quantity.to_i, variety_name: variety_name)
        end
      end
    end
    @order.save
  end

  def fill_order(slug)
    @order = Order.find_by(slug: slug)
    session[:participants_added][slug] = session[:participants_added][slug] || []
    params[:input_order].permit!
    params[:input_order]['q'].to_h.map do |person_id, varieties_chosen|
      person_name = params[:input_order]['name'][person_id]
      person_name_previous = params[:input_order]['previous_name'][person_id]
      varieties_chosen.map do |variety_id, quantity|
        variety_name = get_variety_name(@order, variety_id)
        detail = search_detail(person_name_previous, variety_name)
        if detail
          update_detail(detail, person_name, quantity)
          session[:participants_added][slug].delete(person_name_previous)
          unless session[:participants_added][slug].include?(person_name) || !person_name.present?
            session[:participants_added][slug] << person_name
          end
        else
          if quantity.to_i != 0
            @order.order_details << OrderDetail.new(person: person_name, order_id: @order.id, quantity: quantity.to_i, variety_name: variety_name)
            unless session[:participants_added][slug].include?(person_name) || !person_name.present?
              session[:participants_added][slug] << person_name
            end
          end
        end
      end
    end
    @order.save
  end

  def search_detail(person, variety_name)
    @order.order_details.find_by(person: person, variety_name: variety_name)
  end

  def update_detail(detail, person, quantity)
    if detail
      if quantity.to_i == 0
        detail.destroy
      else
        detail.update(person: person, quantity: quantity.to_i)
      end
    end
    detail
  end

  def get_variety_name(order, variety_id)
    if order.place_id
      variety = Variety.find_by(id: variety_id)
      variety_name = variety.name
    else
      variety_name = params[:input_order][:variety][variety_id.to_s]
    end
    variety_name
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_message.html.erb
<h1>Pedido para <%= @order.place_name %></h1>
<h3>
  Invita a tus compañeros: <%= @order.slug %>
  <button title='Copiar' id = "linkOfer" class="btn btn-secondary btn-sm"><i class="far fa-copy"></i> Copiar link</button>
</h3>
<div id="alert_linkOfer"></div>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/orders/_summary.html.erb
<thead>
<tr>
  <th scope="col">Variedad</th>
  <th scope="col">Total por variedad</th>
  <% @order.list_of_participants.each do |person_name| %>
    <th scope="col"><%= person_name %></th>
  <% end %>
</tr>
</thead>
<tbody>
<% @order.varieties_to_buy.each do |variety| %>
  <tr>
    <td id="column"><%= variety %></td>
    <td id="column"><%= @order.total_units_per_variety[variety] %></td>
    <% @order.list_of_participants.each do |person_name| %>
      <% detail = @order.order_details.select {|d| d.person == person_name && d.variety_name == variety} %>
        <% if detail.length > 0 %>
          <td id="column"><%= detail.sum(&:quantity) %></td>
        <% else %>
          <td id="column">0</td>
        <% end %>
    <% end %>
  </tr>
<% end %>
</tbody>

app/views/orders/confirm.html.erb
<h1>¡Casi estamos!</h1>
<p class="lead">Una vez que te hayas comunicado con el local de comidas, carga el precio para saber cuánto deberá pagar cada
  integrante.</p>
<div class="row">
  <div class="col">
    <h3>Datos del comercio</h3>
    <ul>
      <li><%= @order.place_name %></li>
      <% if @order.place_phone %>
        <li>Teléfono: <%= @order.place_phone %></li>
      <% end %>
    </ul>
  </div>
</div>
<table class="table table-striped table-responsive">
  <%= render partial: 'summary' %>
  <tfoot>
  <tr>
    <td id="column"><strong>Total de empanadas</strong></td>
    <td id="column"><strong><%= @order.total_units %></strong></td>
    <% @order.list_of_participants.each do |person| %>
      <td id="column"><%= @order.total_units_per_person[person] %></td>
    <% end %>
  </tr>
  </tfoot>
</table>
<div class="row">
  <div class="col-md-5">
    <%= form_for :order_data, url: finish_order_path do |f| %>
      <div class="form-group">
        <p><strong>¿Cuál es el costo del pedido?</strong></p>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">$</span>
          </div>
          <%= f.text_field 'price', class: 'form-control' %>
        </div>
      </div>
      <%= f.submit 'Ya ordené el pedido', class: 'btn btn-primary mb-1' %>
      <%= f.submit 'Quiero volver a editar', class: 'btn btn-secondary mb-1' %>
    <% end %>
  </div>
</div>

app/views/orders/create.html.erb
<h1>Finalizar pedido</h1>
<div class="row">
  <div class="col">
    <h3>Datos del comercio</h3>
    <ul>
      <li><%= session[:place]['name'] %></li>
      <li>Teléfono: <%= session[:place]['phone'] %></li>
    </ul>
  </div>
</div>
<table class="table table-striped">
  <%= render partial: 'summary' %>
  <tfoot>
  <tr>
    <td><strong>Total de empanadas</strong></td>
    <td><strong><%= @order.total_units %></strong></td>
    <% @order.list_of_participants.each do |person| %>
      <td><%= @order.total_units_per_person[person] %></td>
    <% end %>
  </tr>
  </tfoot>
</table>
<%= form_for :price, url: finish_order_path do |f| %>
  <div class="form-group">
    <%= f.label 'Precio' %>
    <%= f.text_field 'price', required:true, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-primary">Finalizar</button>
<% end %>

app/views/orders/edit.html.erb
<%= render partial: 'message' %>
<div class="row">
  <div class="col">
    <%= form_for :input_order, url: orders_path do |f| %>
      <%= f.submit :Pedir, class: "btn btn-primary" %>
      <p></p>
      <%= f.hidden_field 'slug', value: @order.slug %>
      <table class="table table-borderless table-striped table-responsive">
        <thead>
        <th></th>
        <th scope="col" colspan=8 id="nombres-integrantes">Nombres de los integrantes del pedido</th>
        <tr>
          <th scope="col">Variedad</th>
          <% participants = session[:participants_added][@order.slug] || [] %>
          <% extern_participants = @order.list_of_participants - participants %>
          <% participants.length.times do |x| %>
            <th scope="col">
              <%= f.text_field "name[#{x}]", value: participants[x], class: 'form-control' %>
            </th>
            <%= f.hidden_field "previous_name[#{x}]", value: participants[x], class: 'form-control' %>
          <% end %>
          <% (extern_participants.length).times do |x| %>
            <th scope="col">
              <%= extern_participants[x] %>
            </th>
          <% end %>
          <% blank_fields = 8 - participants.length - extern_participants.length %>
          <% if blank_fields > 0 %>
            <% blank_fields.times do |x| %>
              <th scope="col">
                <%= f.text_field "name[#{x + participants.length}]", class: 'form-control' %>
              </th>
              <%= f.hidden_field "previous_name[#{x + participants.length}]", value: "", class: 'form-control' %>
            <% end %>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @order.place.varieties.each do |variety| %>
          <tr>
            <td id="column"><%= variety.name %></td>
            <% participants.length.times do |x| %>
              <td id="column"><%= f.number_field "q[#{x}][#{variety.id}]", min: 0, value: @order.search_quantity(participants[x], variety.name), class: 'form-control' %></td>
            <% end %>
            <% extern_participants.length.times do |x| %>
              <td id="column"><%= @order.search_quantity(extern_participants[x], variety.name) %></td>
            <% end %>
            <% if blank_fields > 0 %>
              <% blank_fields.times do |x| %>
                <td id="column"><%= f.number_field "q[#{x + participants.length}][#{variety.id}]", min: 0, value: 0, class: 'form-control' %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= f.submit :Guardar, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

<script>
    bootstrap_alert = function () {
    }
    bootstrap_alert.warning = function (message) {
      $('#alert_linkOfer').html('<div class="alert alert-success" role="alert">' + message + '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>')
    }

    $('#linkOfer').on('click', function () {
        var aux = document.createElement("input");
        aux.setAttribute("value", window.location.href);
        document.body.appendChild(aux);
        aux.select();
        document.execCommand("copy");
        document.body.removeChild(aux);
        bootstrap_alert.warning('Se copió con éxito la dirección a la orden, ya puedes compartirla con tus compañeros');
    });
</script>​

app/views/orders/edit_custom_place.html.erb
<%= render partial: 'message' %>
<div class="row">
  <div class="col">
    <%= form_for :input_order, url: orders_path do |f| %>
      <%= f.submit :Pedir, class: "btn btn-primary" %>
      <p></p>
      <%= f.hidden_field 'slug', value: @order.slug %>
      <table class="table table-borderless table-striped table-responsive">
        <thead>
        <th></th>
        <th scope="col" colspan=8 id="nombres-integrantes">Nombres de los integrantes del pedido</th>
        <tr>
          <th scope="col">Variedad</th>
          <% participants = session[:participants_added][@order.slug] || [] %>
          <% extern_participants = @order.list_of_participants - participants %>
          <% participants.length.times do |x| %>
            <th scope="col">
              <%= f.text_field "name[#{x}]", value: participants[x], class: 'form-control' %>
            </th>
            <%= f.hidden_field "previous_name[#{x}]", value: participants[x], class: 'form-control' %>
          <% end %>
          <% (extern_participants.length).times do |x| %>
            <th scope="col">
              <%= extern_participants[x] %>
            </th>
          <% end %>
          <% blank_fields = 8 - participants.length - extern_participants.length %>
          <% if blank_fields > 0 %>
            <% blank_fields.times do |x| %>
              <th scope="col">
                <%= f.text_field "name[#{x + participants.length}]", class: 'form-control' %>
              </th>
              <%= f.hidden_field "previous_name[#{x + participants.length}]", value: "", class: 'form-control' %>
            <% end %>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% varieties = @order.varieties_to_buy %>
        <% (varieties.length).times do |v| %>
          <tr>
            <td id="column">
              <%= varieties[v] %>
              <%= f.text_field "variety[#{v}]", value: varieties[v], type: 'hidden' %>
            </td>
            <% participants.length.times do |x| %>
              <td id="column"><%= f.number_field "q[#{x}][#{v}]", min: 0, value: @order.search_quantity(participants[x], varieties[v]), class: 'form-control' %></td>
            <% end %>
            <% extern_participants.length.times do |x| %>
              <td id="column"><%= @order.search_quantity(extern_participants[x], varieties[v]) %></td>
            <% end %>
            <% if blank_fields > 0 %>
              <% blank_fields.times do |x| %>
                <td id="column"><%= f.number_field "q[#{x + participants.length}][#{v}]", min: 0, value: 0, class: 'form-control' %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        <% (5 - varieties.length).times do |v| %>
          <tr>
            <td id="column"><%= f.text_field "variety[#{v + varieties.length}]", placeholder: 'Variedad', class: 'form-control' %></td>
            <% participants.length.times do |x| %>
              <td id="column"><%= f.number_field "q[#{x}][#{v + varieties.length}]", min: 0, value: 0, class: 'form-control' %></td>
            <% end %>
            <% extern_participants.length.times do |x| %>
              <td id="column">0</td>
            <% end %>
            <% if blank_fields > 0 %>
              <% blank_fields.times do |x| %>
                <td id="column"><%= f.number_field "q[#{x + participants.length}][#{v + varieties.length}]", min: 0, value: 0, class: 'form-control' %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= f.submit :Guardar, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

<script>
    bootstrap_alert = function () {
    }
    bootstrap_alert.warning = function (message) {
        $('#alert_linkOfer').html('<div class="alert alert-success" role="alert">' + message + '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>')
    }

    $('#linkOfer').on('click', function () {
        var aux = document.createElement("input");
        aux.setAttribute("value", window.location.href);
        document.body.appendChild(aux);
        aux.select();
        document.execCommand("copy");
        document.body.removeChild(aux);
        bootstrap_alert.warning('Se copió con éxito la dirección a la orden, ya puedes compartirla con tus compañeros');
    });
</script>​

app/views/orders/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<div class="jumbotron jumbo1tron-fluid">
  <div class="container">
    <h1 class="display-5">Tus problemas para pedir empanadas son historia</h1>
    <p class="lead">¡Con empanadeitor podrás organizar o unirte a pedidos que se hagan
      en tu oficina con un solo click!</p>
  </div>
</div>

<h2><strong>¿Cómo empezar?</strong></h2>

<div class="row">
  <div class="col">
    <h4>Puedes</h4>
    <h3>Armar un pedido</h3>
    <div class="alert alert-info" role="alert">
      <i class="fas fa-info-circle"></i>
      ¿No encuentras tu lugar en la lista?
      Crea una orden llenando el lugar personalizado
    </div>
    <table class="table table-borderless table-striped">
      <thead>
      <th>Lugares para comenzar pedido</th>
      </thead>
      <tbody>
      <div class="row">
        <tr>
          <%= form_for :custom_place, method: :get, class: 'inline-form', url: new_custom_place_orders_path do |f| %>
            <td><%= f.text_field :name, required: true, placeholder: 'Lugar personalizado', class: 'form-control' %></td>
            <td>
              <button type="submit" class="btn btn-primary btn-sm" %>Crear orden</button>
            </td>
          <% end %>

        </tr>
      </div>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td>
            <%= link_to 'Crear orden', new_order_path(place_id: place.id), class: 'btn btn-primary btn-sm' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-3">
    <h4>O bien</h4>
    <h3>Unirte a un pedido iniciado por alguien</h3>

    <%= form_for :join_order, url: send_order_slug_orders_path do |f| %>
      <%= f.text_field :slug, class: 'form-control', required: true, placeholder: 'Código de invitación' %>
      <br>
      <button type="submit" class="btn btn-primary btn-sm" %>Unirse</button>
    <% end %>
  </div>
</div>
      <br>

app/views/orders/join.html.erb
<h1>Pedido para <%= @order.place_name %></h1>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<div class="row">
  <div class="col">
    <%= form_for :input_order, url: create_join_order_path do |f| %>
      <%= f.hidden_field 'slug', value: @order.slug %>
      <table class="table table-striped table-responsive">
        <thead>
        <th></th>
        <th scope="col" colspan=8 id="nombres-integrantes">Nombres de los integrantes del pedido</th>
        <tr>
          <th scope="col">Variedad</th>
          <% participants = @order.list_of_participants %>
          <% if !session[:current_user].presence %>
            <th scope="col"><%= f.text_field "name", placeholder: 'Tu nombre', class: 'form-control' %></th>
          <% else %>
            <th scope="col"><%= session[:current_user] %></th>
          <% end %>
          <% participants.each do |participant| %>
            <% if participant != session[:current_user] %>
              <th scope="col"><%= participant %> </th>
            <% end %>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% if @order.place %>
          <% @order.place.varieties.each do |variety| %>
            <tr>
              <td id="column"><%= variety.name %></td>
              <td id="column"><%= f.number_field "q[#{variety.id}]", min: 0, value: @order.search_quantity(session[:current_user], variety.name), class: 'form-control' %></td>
              <% participants.each do |participant| %>
                <% if participant != session[:current_user] %>
                  <td id="column">
                    <%= @order.search_quantity(participant, variety.name) %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <% varieties = @order.varieties_to_buy %>
          <% varieties.length.times do |v| %>
            <tr>
              <td id="column"><%= varieties[v] %>
                <%= f.text_field "variety[#{v}]", value: varieties[v], type: 'hidden' %>
              </td>
              <td id="column"><%= f.number_field "q[#{v}]", min: 0, value: @order.search_quantity(session[:current_user], varieties[v]), class: 'form-control' %></td>
              <% participants.each do |participant| %>
                <% if participant != session[:current_user] %>
                  <td id="column">
                    <%= @order.search_quantity(participant, varieties[v]) %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
          <% (5 - varieties.length).times do |v| %>
            <tr>
              <td id="column"><%= f.text_field "variety[#{v + varieties.length}]", class: 'form-control', placeholder: 'Variedad' %></td>
              <td><%= f.number_field "q[#{v + varieties.length}]", min: 0, value: 0, class: 'form-control' %></td>
              <% if !session[:current_user].present? || !participants.include?(session[:current_user]) %>
                <% (participants.length).times do |x| %>
                  <td>0</td>
                <% end %>
              <% else %>
                <% (participants.length - 1).times do |x| %>
                  <td id="column">0</td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
      <%= f.submit 'Enviar Preferencias', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/orders/newOrder.html.erb
<h1>Pedido para <%= @place.name %></h1>
<div class="row">
  <div class="col">
    <%= form_for :order, url: create_order_path do |f| %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Variedad</th>
          <% 8.times do |x| %>
            <th scope="col"><%= f.text_field "name[#{x}]", class: 'form-control' %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @place.varieties.each do |variety| %>
          <tr>
            <td><%= variety.name %></td>
            <% 8.times do |x| %>
              <td><%= f.number_field "q[#{variety.id}][#{x}]", min: 0, value: 0 ,class: 'form-control' %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <button type="submit" class="btn btn-primary">Pedir</button>
    <% end %>
  </div>
</div>

app/views/orders/new_order.html.erb
<h1>Pedido para <%= @place.name %></h1>
<div class="row">
  <div class="col">
    <%= form_for :order, url: create_order_path do |f| %>
      <table class="table table-striped">
        <thead>
        <th></th>
        <th scope="col" colspan = 8 id="nombres-integrantes">Nombres de los integrantes del pedido</th>
        <tr>
          <th scope="col">Variedad</th>
          <% 8.times do |x| %>
            <th scope="col"><%= f.text_field "name[#{x}]", class: 'form-control' %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @place.varieties.each do |variety| %>
          <tr>
            <td><%= variety.name %></td>
            <% 8.times do |x| %>
              <td><%= f.number_field "q[#{x}][#{variety.id}]", min: 0, value: 0 ,class: 'form-control' %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <button type="submit" class="btn btn-primary">Pedir</button>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Finalizar pedido</h1>
<div class="row">
  <div class="col">
    <h3>Datos del comercio</h3>
    <ul>
      <li><%= @order.place_name %></li>
      <li>Teléfono: <%= @order.place_phone %></li>
    </ul>
  </div>
</div>
<table class="table table-striped">
  <%= render partial: 'summary' %>
  <tfoot>
  <tr>
    <td><strong>Total de empanadas</strong></td>
    <td><strong><%= @order.total_units %></strong></td>
    <% @order.list_of_participants.each do |person| %>
      <td><%= @order.total_units_per_person[person] %></td>
    <% end %>
  </tr>
  </tfoot>
</table>
<%= form_for :order_data, url: finish_order_path do |f| %>
  <div class="form-group">
    <%= f.label 'Precio' %>
    <%= f.text_field 'price', required: true, class: 'form-control' %>
  </div>
  <%= f.button 'Finalizar', class: 'btn btn-primary' %>
<% end %>