config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :places do
      resources :varieties, except: [:index, :show]
    end
    root 'places#index'
  end
  resources :orders, only: [:index, :new, :create, :show], param: :slug do
    get :new_custom_place, on: :collection, to: 'orders#new_custom_place'
    post :finish, on: :member
    post :create_join, on: :member
    post :send_order_slug, on: :collection
  end
  root 'orders#index'
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Empanadeitor - Administrador</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

 <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"></head>

<body>
<nav class="navbar navb-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=<%= root_path %>>Empanadeitor</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= admin_places_path %>>Lugares</a>
      </li>
    </ul>
</nav>


<div class="container">    
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Empanadeitor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <% if Rails.env.production? %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68424725-2"></script>
      <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-68424725-2');
      </script>
  <% end %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href=<%= root_path %>>Empanadeitor</a>
  <img src="<%= asset_path 'wecode.png' %>" width="30" height="30" alt="">
  <div>
    <ul class="social-network social-circle">
      <li>
        <a href='https://www.facebook.com/wecodeio' target='_blank' title="Facebook"><i class="fa fa-facebook"></i></a>
      </li>
      <li>
        <a href='https://twitter.com/wecodeio' target='_blank' title="Twitter"><i class="fa fa-twitter"></i></a>
      </li>
      <li>
        <a href='https://instagram.com/wecodeio' target='_blank' title="Instagram"><i class='fa fa-instagram'></i></a>
      </li>
    </ul>
  </div>
</nav>

<a id="fork-me" class="d-none d-md-block" href="https://github.com/wecodeio/empanadeitor">
  <img width="149" height="149"
       src="https://github.blog/wp-content/uploads/2008/12/forkme_left_red_aa0000.png?resize=149%2C149"
       class="attachment-full size-full" alt="Fork me on GitHub" data-recalc-dims="1">
</a>

<div class="container mt-4 mb-5">
  <%= yield %>
</div>

<footer class="fixed-bottom">
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <p id="footer-content">Hecho con <i class="fas fa-heart"></i>
          por el equipo M de <a href="https://wecode.io/en/">WeCode</a></p>
        </a>
      </div>
    </div>
  </div>
</footer>
</body>
</html>